# ArxOne FTP appveyor.yml script

branches:
  only:
    - master
    - new-tests

version: '{branch}-{build}'

os: Visual Studio 2017

before_build:
  nuget restore

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release
platform: Any CPU

build:
  parallel: false
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal

deploy:
  provider: NuGet
  api_key:
    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
  skip_symbols: false
