# ArxOne FTP appveyor.yml script

branches:
  only:
    - master
    - new-tests

version: '{branch}-{build}'

os: Visual Studio 2017

before_build:
  nuget restore

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release

build:
  parallel: false
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: QsAfyY+46GeTCjC+L2kjV6/1AriR3nxjHm8EUru4epPuwl9IHaqAlC13H5TCWyBF
  skip_symbols: false
